In [12]:
%pip install pandas

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)

Requirement already satisfied: pandas in c:\users\shrey\appdata\local\programs\python\python312\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\shrey\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shrey\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\shrey\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\shrey\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\shrey\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
# Load datasets
diabetic_df = pd.read_csv("C:/internship/datasets/raw/diabetic_data.csv")
ids_mapping_df = pd.read_csv("C:/internship/datasets/raw/IDS_mapping.csv")

In [14]:
# Shape
print("Diabetic data shape:", diabetic_df.shape)
print("IDS mapping shape:", ids_mapping_df.shape)

Diabetic data shape: (101766, 50)
IDS mapping shape: (67, 2)

In [15]:
# Replace encoded missing values
diabetic_df = diabetic_df.replace("?", np.nan)

In [16]:
# Verify no "?" remains
(diabetic_df == "?").sum()

encounter_id                0
patient_nbr                 0
race                        0
gender                      0
age                         0
weight                      0
admission_type_id           0
discharge_disposition_id    0
admission_source_id         0
time_in_hospital            0
payer_code                  0
medical_specialty           0
num_lab_procedures          0
num_procedures              0
num_medications             0
number_outpatient           0
number_emergency            0
number_inpatient            0
diag_1                      0
diag_2                      0
diag_3                      0
number_diagnoses            0
max_glu_serum               0
A1Cresult                   0
metformin                   0
repaglinide                 0
nateglinide                 0
chlorpropamide              0
glimepiride                 0
acetohexamide               0
glipizide                   0
glyburide                   0
tolbutamide                 0
pioglitazone                0
rosiglitazone               0
acarbose                    0
miglitol                    0
troglitazone                0
tolazamide                  0
examide                     0
citoglipton                 0
insulin                     0
glyburide-metformin         0
glipizide-metformin         0
glimepiride-pioglitazone    0
metformin-rosiglitazone     0
metformin-pioglitazone      0
change                      0
diabetesMed                 0
readmitted                  0
dtype: int64

In [17]:
missing_audit = (
    diabetic_df.isna()
    .sum()
    .to_frame(name="missing_count")
)

missing_audit["missing_pct"] = (
    missing_audit["missing_count"] / len(diabetic_df) * 100
)

missing_audit = missing_audit.sort_values(
    by="missing_pct", ascending=False
)

In [18]:
missing_audit

                          missing_count  missing_pct
weight                            98569    96.858479
max_glu_serum                     96420    94.746772
A1Cresult                         84748    83.277322
medical_specialty                 49949    49.082208
payer_code                        40256    39.557416
race                               2273     2.233555
diag_3                             1423     1.398306
diag_2                              358     0.351787
diag_1                               21     0.020636
patient_nbr                           0     0.000000
time_in_hospital                      0     0.000000
admission_source_id                   0     0.000000
num_lab_procedures                    0     0.000000
encounter_id                          0     0.000000
admission_type_id                     0     0.000000
discharge_disposition_id              0     0.000000
gender                                0     0.000000
age                                   0     0.000000
number_inpatient                      0     0.000000
number_emergency                      0     0.000000
number_outpatient                     0     0.000000
num_medications                       0     0.000000
num_procedures                        0     0.000000
number_diagnoses                      0     0.000000
metformin                             0     0.000000
repaglinide                           0     0.000000
nateglinide                           0     0.000000
chlorpropamide                        0     0.000000
glimepiride                           0     0.000000
acetohexamide                         0     0.000000
glipizide                             0     0.000000
glyburide                             0     0.000000
tolbutamide                           0     0.000000
pioglitazone                          0     0.000000
rosiglitazone                         0     0.000000
acarbose                              0     0.000000
miglitol                              0     0.000000
troglitazone                          0     0.000000
tolazamide                            0     0.000000
examide                               0     0.000000
citoglipton                           0     0.000000
insulin                               0     0.000000
glyburide-metformin                   0     0.000000
glipizide-metformin                   0     0.000000
glimepiride-pioglitazone              0     0.000000
metformin-rosiglitazone               0     0.000000
metformin-pioglitazone                0     0.000000
change                                0     0.000000
diabetesMed                           0     0.000000
readmitted                            0     0.000000

In [19]:
diabetic_df["readmit_30"] = np.where(
    diabetic_df["readmitted"] == "<30",
    1,
    0
)

In [25]:
diabetic_df["readmit_30"].value_counts(dropna=False)

readmit_30
0    90409
1    11357
Name: count, dtype: int64

In [26]:
# Cross-check against original
pd.crosstab(diabetic_df["readmitted"], diabetic_df["readmit_30"])

readmit_30      0      1
readmitted
<30             0  11357
>30         35545      0
NO          54864      0

In [22]:
identifier_columns = [
    "encounter_id",
    "patient_nbr"
]

identifier_columns

['encounter_id', 'patient_nbr']

In [23]:
diabetic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 51 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      99493 non-null   object
 3   gender                    101766 non-null  object
 4   age                       101766 non-null  object
 5   weight                    3197 non-null    object
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                61510 non-null   object
 11  medical_specialty         51817 non-null   object
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101745 non-null  object
 19  diag_2                    101408 non-null  object
 20  diag_3                    100343 non-null  object
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             5346 non-null    object
 23  A1Cresult                 17018 non-null   object
 24  metformin                 101766 non-null  object
 25  repaglinide               101766 non-null  object
 26  nateglinide               101766 non-null  object
 27  chlorpropamide            101766 non-null  object
 28  glimepiride               101766 non-null  object
 29  acetohexamide             101766 non-null  object
 30  glipizide                 101766 non-null  object
 31  glyburide                 101766 non-null  object
 32  tolbutamide               101766 non-null  object
 33  pioglitazone              101766 non-null  object
 34  rosiglitazone             101766 non-null  object
 35  acarbose                  101766 non-null  object
 36  miglitol                  101766 non-null  object
 37  troglitazone              101766 non-null  object
 38  tolazamide                101766 non-null  object
 39  examide                   101766 non-null  object
 40  citoglipton               101766 non-null  object
 41  insulin                   101766 non-null  object
 42  glyburide-metformin       101766 non-null  object
 43  glipizide-metformin       101766 non-null  object
 44  glimepiride-pioglitazone  101766 non-null  object
 45  metformin-rosiglitazone   101766 non-null  object
 46  metformin-pioglitazone    101766 non-null  object
 47  change                    101766 non-null  object
 48  diabetesMed               101766 non-null  object
 49  readmitted                101766 non-null  object
 50  readmit_30                101766 non-null  int64
dtypes: int64(14), object(37)
memory usage: 39.6+ MB

In [24]:
# Save missing value audit
missing_audit.to_csv(
    "missing_value_audit.csv",
    index=True
)

# Save cleaned base table (still mostly raw)
diabetic_df.to_csv(
    "diabetic_data_base_table.csv",
    index=False
)